// tb_inv.cpp
#include "Vtop.h"            // Top-level module generated by Verilator
#include "verilated.h"       // Verilator header
#include "verilated_vcd_c.h" // For VCD dump

int main(int argc, char** argv) {
    // Initialize Verilator with command-line arguments.
    Verilated::commandArgs(argc, argv);

    // Call it before `new` to enable wave trace
    Verilated::traceEverOn(true);

    // DUT (Device Under Test)
    Vtop* top = new Vtop;

    // VCD dump config
    VerilatedVcdC* tfp = new VerilatedVcdC;
    top->trace(tfp, 99);       // trace level (optional)
    tfp->open("waveform.vcd"); // output file

    // Run simulation
    const int sim_time_max =
        1000; // Simulation end time, integer, in increments of 10
    for (int sim_time = 0; sim_time < sim_time_max; sim_time += 10) {
        top->clk = !top->clk;
        top->eval();            // Evaluate DUT
        tfp->dump(sim_time);    // Dump the wave at the current time
        Verilated::timeInc(10); // increment 10ns
    }

    // Close
    tfp->close();
    delete top;

    return 0;
}

